# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c68f5671ebe0287e3b282b0a2bb0dce"
name = "soupjian-app"
application_url = "https://zip-links-maker-streets.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-soupjian.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://zip-links-maker-streets.trycloudflare.com/auth/callback",
  "https://zip-links-maker-streets.trycloudflare.com/auth/shopify/callback",
  "https://zip-links-maker-streets.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
